#!/bin/sh
# Here's an example script for a hostmaster of a large site
# to automate the process
# You can also run "./makereports <logfile" to generate an error report for
# each hostmaster.  Then cd to the rep.orts directory, remove any files
# you don't wish to send, then run "../sendreports"
# try adding '-F' here once just to see what pops up
flags='-r -d'
logfile=podunk.errors
trap "" 2 15;
exec > ${logfile}
./dnswalk ${flags} $* podunk.edu.
./dnswalk ${flags} $* 1.1.in-addr.arpa.
./dnswalk ${flags} $* 2.1.in-addr.arpa.
./dnswalk ${flags} $* 1.2.1.in-addr.arpa.
./dnswalk ${flags} $* 2.2.1.in-addr.arpa.
